language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:1.0.0"
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database test;'
  - mysql -e 'create database test2;'
  - mysql -u root test < tests/data/test.sql
  - mysql -u root test2 < tests/data/test2.sql

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
